version: '3.8' 

services:
  pokemon_game_web:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: pokemon_game_php 
    ports:
      - "8080:80" 
    volumes:
      - .:/var/www/html 
    restart: unless-stopped 
    environment:

      PHP_INI_DISPLAY_ERRORS: "On" 
      PHP_INI_ERROR_REPORTING: E_ALL

networks:
  default: 